version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      three:
        patterns:
          - "three"
          - "@types/three"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "globals"
          - "@stylistic/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
