import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_PART_7: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x3x6",
    name: "Schaller 3x6 - 3 inch depth",
    sku: "SCH-336",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 5.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x12",
    name: "Schaller 3x12 - 3 inch depth",
    sku: "SCH-3312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 12 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 11.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x4",
    name: "Schaller 4x4 - 3 inch depth",
    sku: "SCH-344",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 4.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x6",
    name: "Schaller 4x6 - 3 inch depth",
    sku: "SCH-346",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x6x6",
    name: "Schaller 6x6 - 3 inch depth",
    sku: "SCH-366",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 6 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 5.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
