import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_PART_2: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-2x1x2",
    name: "Schaller 1x2 - 2 inch depth",
    sku: "SCH-212",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x3",
    name: "Schaller 1x3 - 2 inch depth",
    sku: "SCH-213",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x4",
    name: "Schaller 1x4 - 2 inch depth",
    sku: "SCH-214",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x6",
    name: "Schaller 1x6 - 2 inch depth",
    sku: "SCH-216",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x2",
    name: "Schaller 2x2 - 2 inch depth",
    sku: "SCH-222",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
];
