import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_7: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x3x6",
    name: "Schaller 3x6 - 3 inch depth",
    sku: "SCH-336",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(6),
    nominalH: inches(3),
    actualW: inches(2.9),
    actualL: inches(5.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 5.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x12",
    name: "Schaller 3x12 - 3 inch depth",
    sku: "SCH-3312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(12),
    nominalH: inches(3),
    actualW: inches(2.9),
    actualL: inches(11.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x4",
    name: "Schaller 4x4 - 3 inch depth",
    sku: "SCH-344",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(4),
    nominalL: inches(4),
    nominalH: inches(3),
    actualW: inches(3.9),
    actualL: inches(3.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 4.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x6",
    name: "Schaller 4x6 - 3 inch depth",
    sku: "SCH-346",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(4),
    nominalL: inches(6),
    nominalH: inches(3),
    actualW: inches(3.9),
    actualL: inches(5.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x6x6",
    name: "Schaller 6x6 - 3 inch depth",
    sku: "SCH-366",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(6),
    nominalL: inches(6),
    nominalH: inches(3),
    actualW: inches(5.9),
    actualL: inches(5.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
