import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_PART_1: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-1x2x3",
    name: "Schaller 2x3 - 1 inch depth",
    sku: "SCH-123",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x4",
    name: "Schaller 2x4 - 1 inch depth",
    sku: "SCH-124",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x6",
    name: "Schaller 2x6 - 1 inch depth",
    sku: "SCH-126",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x3",
    name: "Schaller 3x3 - 1 inch depth",
    sku: "SCH-133",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 1 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.90,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x6",
    name: "Schaller 3x6 - 1 inch depth",
    sku: "SCH-136",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 1 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
