import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_1: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-1x2x3",
    name: "Schaller 2x3 - 1 inch depth",
    sku: "SCH-123",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(3),
    nominalH: inches(1),
    actualW: inches(1.9),
    actualL: inches(2.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x4",
    name: "Schaller 2x4 - 1 inch depth",
    sku: "SCH-124",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(4),
    nominalH: inches(1),
    actualW: inches(1.9),
    actualL: inches(3.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x6",
    name: "Schaller 2x6 - 1 inch depth",
    sku: "SCH-126",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(6),
    nominalH: inches(1),
    actualW: inches(1.9),
    actualL: inches(5.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x3",
    name: "Schaller 3x3 - 1 inch depth",
    sku: "SCH-133",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(3),
    nominalH: inches(1),
    actualW: inches(2.9),
    actualL: inches(2.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.90,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x6",
    name: "Schaller 3x6 - 1 inch depth",
    sku: "SCH-136",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(6),
    nominalH: inches(1),
    actualW: inches(2.9),
    actualL: inches(5.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
