import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_PART_3: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-2x2x3",
    name: "Schaller 2x3 - 2 inch depth",
    sku: "SCH-223",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x4",
    name: "Schaller 2x4 - 2 inch depth",
    sku: "SCH-224",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x6",
    name: "Schaller 2x6 - 2 inch depth",
    sku: "SCH-226",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x3",
    name: "Schaller 3x3 - 2 inch depth",
    sku: "SCH-233",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x4",
    name: "Schaller 3x4 - 2 inch depth",
    sku: "SCH-234",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
