import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_6: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x2x3",
    name: "Schaller 2x3 - 3 inch depth",
    sku: "SCH-323",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(3),
    nominalH: inches(3),
    actualW: inches(1.9),
    actualL: inches(2.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x4",
    name: "Schaller 2x4 - 3 inch depth",
    sku: "SCH-324",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(4),
    nominalH: inches(3),
    actualW: inches(1.9),
    actualL: inches(3.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x6",
    name: "Schaller 2x6 - 3 inch depth",
    sku: "SCH-326",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(6),
    nominalH: inches(3),
    actualW: inches(1.9),
    actualL: inches(5.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x3",
    name: "Schaller 3x3 - 3 inch depth",
    sku: "SCH-333",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(3),
    nominalH: inches(3),
    actualW: inches(2.9),
    actualL: inches(2.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 2.70,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x4",
    name: "Schaller 3x4 - 3 inch depth",
    sku: "SCH-334",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(4),
    nominalH: inches(3),
    actualW: inches(2.9),
    actualL: inches(3.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
