import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_4: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-2x3x6",
    name: "Schaller 3x6 - 2 inch depth",
    sku: "SCH-236",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(6),
    nominalH: inches(2),
    actualW: inches(2.9),
    actualL: inches(5.9),
    actualH: inches(1.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x12",
    name: "Schaller 3x12 - 2 inch depth",
    sku: "SCH-2312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(3),
    nominalL: inches(12),
    nominalH: inches(2),
    actualW: inches(2.9),
    actualL: inches(11.9),
    actualH: inches(1.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x4",
    name: "Schaller 4x4 - 2 inch depth",
    sku: "SCH-244",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(4),
    nominalL: inches(4),
    nominalH: inches(2),
    actualW: inches(3.9),
    actualL: inches(3.9),
    actualH: inches(1.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 3.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x6",
    name: "Schaller 4x6 - 2 inch depth",
    sku: "SCH-246",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(4),
    nominalL: inches(6),
    nominalH: inches(2),
    actualW: inches(3.9),
    actualL: inches(5.9),
    actualH: inches(1.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 4.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x6x6",
    name: "Schaller 6x6 - 2 inch depth",
    sku: "SCH-266",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(6),
    nominalL: inches(6),
    nominalH: inches(2),
    actualW: inches(5.9),
    actualL: inches(5.9),
    actualH: inches(1.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
