import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_5: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x1x2",
    name: "Schaller 1x2 - 3 inch depth",
    sku: "SCH-312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(2),
    nominalH: inches(3),
    actualW: inches(0.9),
    actualL: inches(1.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x3",
    name: "Schaller 1x3 - 3 inch depth",
    sku: "SCH-313",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(3),
    nominalH: inches(3),
    actualW: inches(0.9),
    actualL: inches(2.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.90,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x4",
    name: "Schaller 1x4 - 3 inch depth",
    sku: "SCH-314",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(4),
    nominalH: inches(3),
    actualW: inches(0.9),
    actualL: inches(3.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x6",
    name: "Schaller 1x6 - 3 inch depth",
    sku: "SCH-316",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(6),
    nominalH: inches(3),
    actualW: inches(0.9),
    actualL: inches(5.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x2",
    name: "Schaller 2x2 - 3 inch depth",
    sku: "SCH-322",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(2),
    nominalH: inches(3),
    actualW: inches(1.9),
    actualL: inches(1.9),
    actualH: inches(2.75),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
];
