import { BinSpec } from "../types";
import { inches } from "../../geometry/imperial";

export const SCHALLER_PART_0: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-1x1x2",
    name: "Schaller 1x2 - 1 inch depth",
    sku: "SCH-112",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(2),
    nominalH: inches(1),
    actualW: inches(0.9),
    actualL: inches(1.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x3",
    name: "Schaller 1x3 - 1 inch depth",
    sku: "SCH-113",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(3),
    nominalH: inches(1),
    actualW: inches(0.9),
    actualL: inches(2.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.30,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x4",
    name: "Schaller 1x4 - 1 inch depth",
    sku: "SCH-114",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(4),
    nominalH: inches(1),
    actualW: inches(0.9),
    actualL: inches(3.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x6",
    name: "Schaller 1x6 - 1 inch depth",
    sku: "SCH-116",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(1),
    nominalL: inches(6),
    nominalH: inches(1),
    actualW: inches(0.9),
    actualL: inches(5.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x2",
    name: "Schaller 2x2 - 1 inch depth",
    sku: "SCH-122",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: inches(2),
    nominalL: inches(2),
    nominalH: inches(1),
    actualW: inches(1.9),
    actualL: inches(1.9),
    actualH: inches(1),
    toleranceW: inches(0.02),
    toleranceL: inches(0.02),
    toleranceH: inches(0.02),
    price: 0.40,
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
];
