import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_PART_6: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x2x3",
    name: "Schaller 2x3 - 3 inch depth",
    sku: "SCH-323",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x4",
    name: "Schaller 2x4 - 3 inch depth",
    sku: "SCH-324",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x6",
    name: "Schaller 2x6 - 3 inch depth",
    sku: "SCH-326",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x3",
    name: "Schaller 3x3 - 3 inch depth",
    sku: "SCH-333",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.70,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x4",
    name: "Schaller 3x4 - 3 inch depth",
    sku: "SCH-334",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
