/* eslint-disable max-lines */
import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_2IN: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-2x1x2",
    name: "Schaller 1x2 - 2 inch depth",
    sku: "SCH-212",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x3",
    name: "Schaller 1x3 - 2 inch depth",
    sku: "SCH-213",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x4",
    name: "Schaller 1x4 - 2 inch depth",
    sku: "SCH-214",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x6",
    name: "Schaller 1x6 - 2 inch depth",
    sku: "SCH-216",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x2",
    name: "Schaller 2x2 - 2 inch depth",
    sku: "SCH-222",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80,
    priceApproximate: true,
    colors: ["#e53e3e", "#3182ce"],
  },
  {
    id: "schaller-2x2x3",
    name: "Schaller 2x3 - 2 inch depth",
    sku: "SCH-223",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x4",
    name: "Schaller 2x4 - 2 inch depth",
    sku: "SCH-224",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x6",
    name: "Schaller 2x6 - 2 inch depth",
    sku: "SCH-226",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x3",
    name: "Schaller 3x3 - 2 inch depth",
    sku: "SCH-233",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x4",
    name: "Schaller 3x4 - 2 inch depth",
    sku: "SCH-234",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x6",
    name: "Schaller 3x6 - 2 inch depth",
    sku: "SCH-236",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x12",
    name: "Schaller 3x12 - 2 inch depth",
    sku: "SCH-2312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 12 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 11.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x4",
    name: "Schaller 4x4 - 2 inch depth",
    sku: "SCH-244",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 3.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x6",
    name: "Schaller 4x6 - 2 inch depth",
    sku: "SCH-246",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 3.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 4.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x6x6",
    name: "Schaller 6x6 - 2 inch depth",
    sku: "SCH-266",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 6 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 5.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  }
];
