/* eslint-disable max-lines */
import { BinSpec } from "../types";
import { Inches } from "../../geometry/types";

export const SCHALLER_3IN: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-3x1x2",
    name: "Schaller 1x2 - 3 inch depth",
    sku: "SCH-312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x3",
    name: "Schaller 1x3 - 3 inch depth",
    sku: "SCH-313",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.90,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x4",
    name: "Schaller 1x4 - 3 inch depth",
    sku: "SCH-314",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x6",
    name: "Schaller 1x6 - 3 inch depth",
    sku: "SCH-316",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x2",
    name: "Schaller 2x2 - 3 inch depth",
    sku: "SCH-322",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20,
    priceApproximate: true,
    colors: ["#e53e3e", "#3182ce"],
  },
  {
    id: "schaller-3x2x3",
    name: "Schaller 2x3 - 3 inch depth",
    sku: "SCH-323",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x4",
    name: "Schaller 2x4 - 3 inch depth",
    sku: "SCH-324",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x6",
    name: "Schaller 2x6 - 3 inch depth",
    sku: "SCH-326",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x3",
    name: "Schaller 3x3 - 3 inch depth",
    sku: "SCH-333",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.70,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x4",
    name: "Schaller 3x4 - 3 inch depth",
    sku: "SCH-334",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x6",
    name: "Schaller 3x6 - 3 inch depth",
    sku: "SCH-336",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 5.40,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x12",
    name: "Schaller 3x12 - 3 inch depth",
    sku: "SCH-3312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 12 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 11.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x4",
    name: "Schaller 4x4 - 3 inch depth",
    sku: "SCH-344",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 4.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x6",
    name: "Schaller 4x6 - 3 inch depth",
    sku: "SCH-346",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20,
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x6x6",
    name: "Schaller 6x6 - 3 inch depth",
    sku: "SCH-366",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 6 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 5.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80,
    priceApproximate: true,
    colors: ["#e53e3e"],
  }
];
