/* eslint-disable max-lines */
import { BinSpec } from "./types";
import { Inches } from "../geometry/types";

export const SCHALLER_CATALOG: ReadonlyArray<BinSpec> = [
  {
    id: "schaller-1x1x2",
    name: "Schaller 1x2 - 1 inch depth",
    sku: "SCH-112",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 1 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x3",
    name: "Schaller 1x3 - 1 inch depth",
    sku: "SCH-113",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 1 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.30, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x4",
    name: "Schaller 1x4 - 1 inch depth",
    sku: "SCH-114",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 1 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x1x6",
    name: "Schaller 1x6 - 1 inch depth",
    sku: "SCH-116",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 1 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x2",
    name: "Schaller 2x2 - 1 inch depth",
    sku: "SCH-122",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
  {
    id: "schaller-1x2x3",
    name: "Schaller 2x3 - 1 inch depth",
    sku: "SCH-123",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x4",
    name: "Schaller 2x4 - 1 inch depth",
    sku: "SCH-124",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x2x6",
    name: "Schaller 2x6 - 1 inch depth",
    sku: "SCH-126",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 1 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x3",
    name: "Schaller 3x3 - 1 inch depth",
    sku: "SCH-133",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 1 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.90, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-1x3x6",
    name: "Schaller 3x6 - 1 inch depth",
    sku: "SCH-136",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 1 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x2",
    name: "Schaller 1x2 - 2 inch depth",
    sku: "SCH-212",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x3",
    name: "Schaller 1x3 - 2 inch depth",
    sku: "SCH-213",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x4",
    name: "Schaller 1x4 - 2 inch depth",
    sku: "SCH-214",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x1x6",
    name: "Schaller 1x6 - 2 inch depth",
    sku: "SCH-216",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x2",
    name: "Schaller 2x2 - 2 inch depth",
    sku: "SCH-222",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
  {
    id: "schaller-2x2x3",
    name: "Schaller 2x3 - 2 inch depth",
    sku: "SCH-223",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x4",
    name: "Schaller 2x4 - 2 inch depth",
    sku: "SCH-224",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x2x6",
    name: "Schaller 2x6 - 2 inch depth",
    sku: "SCH-226",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x3",
    name: "Schaller 3x3 - 2 inch depth",
    sku: "SCH-233",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x4",
    name: "Schaller 3x4 - 2 inch depth",
    sku: "SCH-234",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x6",
    name: "Schaller 3x6 - 2 inch depth",
    sku: "SCH-236",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x3x12",
    name: "Schaller 3x12 - 2 inch depth",
    sku: "SCH-2312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 12 as Inches,
    nominalH: 2 as Inches,
    actualW: 2.9 as Inches,
    actualL: 11.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x4",
    name: "Schaller 4x4 - 2 inch depth",
    sku: "SCH-244",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 4 as Inches,
    nominalH: 2 as Inches,
    actualW: 3.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x4x6",
    name: "Schaller 4x6 - 2 inch depth",
    sku: "SCH-246",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 3.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 4.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-2x6x6",
    name: "Schaller 6x6 - 2 inch depth",
    sku: "SCH-266",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 6 as Inches,
    nominalL: 6 as Inches,
    nominalH: 2 as Inches,
    actualW: 5.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 1.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x2",
    name: "Schaller 1x2 - 3 inch depth",
    sku: "SCH-312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 2 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x3",
    name: "Schaller 1x3 - 3 inch depth",
    sku: "SCH-313",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 0.90, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x4",
    name: "Schaller 1x4 - 3 inch depth",
    sku: "SCH-314",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x1x6",
    name: "Schaller 1x6 - 3 inch depth",
    sku: "SCH-316",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 1 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 0.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x2",
    name: "Schaller 2x2 - 3 inch depth",
    sku: "SCH-322",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 2 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 1.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e","#3182ce"],
  },
  {
    id: "schaller-3x2x3",
    name: "Schaller 2x3 - 3 inch depth",
    sku: "SCH-323",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 1.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x4",
    name: "Schaller 2x4 - 3 inch depth",
    sku: "SCH-324",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x2x6",
    name: "Schaller 2x6 - 3 inch depth",
    sku: "SCH-326",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 2 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 1.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x3",
    name: "Schaller 3x3 - 3 inch depth",
    sku: "SCH-333",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 3 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 2.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 2.70, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x4",
    name: "Schaller 3x4 - 3 inch depth",
    sku: "SCH-334",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 3.60, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x6",
    name: "Schaller 3x6 - 3 inch depth",
    sku: "SCH-336",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 5.40, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x3x12",
    name: "Schaller 3x12 - 3 inch depth",
    sku: "SCH-3312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 3 as Inches,
    nominalL: 12 as Inches,
    nominalH: 3 as Inches,
    actualW: 2.9 as Inches,
    actualL: 11.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x4",
    name: "Schaller 4x4 - 3 inch depth",
    sku: "SCH-344",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 4 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 3.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 4.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x4x6",
    name: "Schaller 4x6 - 3 inch depth",
    sku: "SCH-346",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 4 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 3.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 7.20, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
  {
    id: "schaller-3x6x6",
    name: "Schaller 6x6 - 3 inch depth",
    sku: "SCH-366",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    nominalW: 6 as Inches,
    nominalL: 6 as Inches,
    nominalH: 3 as Inches,
    actualW: 5.9 as Inches,
    actualL: 5.9 as Inches,
    actualH: 2.75 as Inches,
    toleranceW: 0.02 as Inches,
    toleranceL: 0.02 as Inches,
    toleranceH: 0.02 as Inches,
    price: 10.80, // approximate pricing formula
    priceApproximate: true,
    colors: ["#e53e3e"],
  },
];
