import { BinSpec, binId } from "./index";
import { inches } from "../geometry/imperial";

export const SCHALLER_CATALOG: ReadonlyArray<BinSpec> = [
  {
    id: binId("schaller-1x1x2"),
    name: "Schaller 1x2 - 1 inch depth",
    sku: "SCH-112",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(2), h: inches(1) },
    actual: { w: inches(0.9), l: inches(1.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x1x3"),
    name: "Schaller 1x3 - 1 inch depth",
    sku: "SCH-113",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(3), h: inches(1) },
    actual: { w: inches(0.9), l: inches(2.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x1x4"),
    name: "Schaller 1x4 - 1 inch depth",
    sku: "SCH-114",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(4), h: inches(1) },
    actual: { w: inches(0.9), l: inches(3.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x1x6"),
    name: "Schaller 1x6 - 1 inch depth",
    sku: "SCH-116",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(6), h: inches(1) },
    actual: { w: inches(0.9), l: inches(5.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x2x2"),
    name: "Schaller 2x2 - 1 inch depth",
    sku: "SCH-122",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(2), h: inches(1) },
    actual: { w: inches(1.9), l: inches(1.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x2x3"),
    name: "Schaller 2x3 - 1 inch depth",
    sku: "SCH-123",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(3), h: inches(1) },
    actual: { w: inches(1.9), l: inches(2.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x2x4"),
    name: "Schaller 2x4 - 1 inch depth",
    sku: "SCH-124",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(4), h: inches(1) },
    actual: { w: inches(1.9), l: inches(3.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x2x6"),
    name: "Schaller 2x6 - 1 inch depth",
    sku: "SCH-126",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(6), h: inches(1) },
    actual: { w: inches(1.9), l: inches(5.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x3x3"),
    name: "Schaller 3x3 - 1 inch depth",
    sku: "SCH-133",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(3), h: inches(1) },
    actual: { w: inches(2.9), l: inches(2.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-1x3x6"),
    name: "Schaller 3x6 - 1 inch depth",
    sku: "SCH-136",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(6), h: inches(1) },
    actual: { w: inches(2.9), l: inches(5.9), h: inches(1) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x2"),
    name: "Schaller 1x2 - 2 inch depth",
    sku: "SCH-212",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(2), h: inches(2) },
    actual: { w: inches(0.9), l: inches(1.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x3"),
    name: "Schaller 1x3 - 2 inch depth",
    sku: "SCH-213",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(3), h: inches(2) },
    actual: { w: inches(0.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x4"),
    name: "Schaller 1x4 - 2 inch depth",
    sku: "SCH-214",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(4), h: inches(2) },
    actual: { w: inches(0.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x6"),
    name: "Schaller 1x6 - 2 inch depth",
    sku: "SCH-216",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(6), h: inches(2) },
    actual: { w: inches(0.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x2"),
    name: "Schaller 2x2 - 2 inch depth",
    sku: "SCH-222",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(2), h: inches(2) },
    actual: { w: inches(1.9), l: inches(1.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x3"),
    name: "Schaller 2x3 - 2 inch depth",
    sku: "SCH-223",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(3), h: inches(2) },
    actual: { w: inches(1.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x4"),
    name: "Schaller 2x4 - 2 inch depth",
    sku: "SCH-224",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(4), h: inches(2) },
    actual: { w: inches(1.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x6"),
    name: "Schaller 2x6 - 2 inch depth",
    sku: "SCH-226",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(6), h: inches(2) },
    actual: { w: inches(1.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x3"),
    name: "Schaller 3x3 - 2 inch depth",
    sku: "SCH-233",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(3), h: inches(2) },
    actual: { w: inches(2.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x4"),
    name: "Schaller 3x4 - 2 inch depth",
    sku: "SCH-234",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(4), h: inches(2) },
    actual: { w: inches(2.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x6"),
    name: "Schaller 3x6 - 2 inch depth",
    sku: "SCH-236",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(6), h: inches(2) },
    actual: { w: inches(2.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x12"),
    name: "Schaller 3x12 - 2 inch depth",
    sku: "SCH-2312",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(12), h: inches(2) },
    actual: { w: inches(2.9), l: inches(11.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x4x4"),
    name: "Schaller 4x4 - 2 inch depth",
    sku: "SCH-244",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(4), h: inches(2) },
    actual: { w: inches(3.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x4x6"),
    name: "Schaller 4x6 - 2 inch depth",
    sku: "SCH-246",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(6), h: inches(2) },
    actual: { w: inches(3.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x6x6"),
    name: "Schaller 6x6 - 2 inch depth",
    sku: "SCH-266",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(6), l: inches(6), h: inches(2) },
    actual: { w: inches(5.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x2"),
    name: "Schaller 1x2 - 3 inch depth",
    sku: "SCH-312",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(2), h: inches(3) },
    actual: { w: inches(0.9), l: inches(1.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x3"),
    name: "Schaller 1x3 - 3 inch depth",
    sku: "SCH-313",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(3), h: inches(3) },
    actual: { w: inches(0.9), l: inches(2.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x4"),
    name: "Schaller 1x4 - 3 inch depth",
    sku: "SCH-314",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(4), h: inches(3) },
    actual: { w: inches(0.9), l: inches(3.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x6"),
    name: "Schaller 1x6 - 3 inch depth",
    sku: "SCH-316",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(1), l: inches(6), h: inches(3) },
    actual: { w: inches(0.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x2x2"),
    name: "Schaller 2x2 - 3 inch depth",
    sku: "SCH-322",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(2), h: inches(3) },
    actual: { w: inches(1.9), l: inches(1.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x2x3"),
    name: "Schaller 2x3 - 3 inch depth",
    sku: "SCH-323",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(3), h: inches(3) },
    actual: { w: inches(1.9), l: inches(2.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x2x4"),
    name: "Schaller 2x4 - 3 inch depth",
    sku: "SCH-324",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(4), h: inches(3) },
    actual: { w: inches(1.9), l: inches(3.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x2x6"),
    name: "Schaller 2x6 - 3 inch depth",
    sku: "SCH-326",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(6), h: inches(3) },
    actual: { w: inches(1.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x3x3"),
    name: "Schaller 3x3 - 3 inch depth",
    sku: "SCH-333",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(3), h: inches(3) },
    actual: { w: inches(2.9), l: inches(2.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x3x4"),
    name: "Schaller 3x4 - 3 inch depth",
    sku: "SCH-334",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(4), h: inches(3) },
    actual: { w: inches(2.9), l: inches(3.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x3x6"),
    name: "Schaller 3x6 - 3 inch depth",
    sku: "SCH-336",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(6), h: inches(3) },
    actual: { w: inches(2.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x3x12"),
    name: "Schaller 3x12 - 3 inch depth",
    sku: "SCH-3312",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(12), h: inches(3) },
    actual: { w: inches(2.9), l: inches(11.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x4x4"),
    name: "Schaller 4x4 - 3 inch depth",
    sku: "SCH-344",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(4), h: inches(3) },
    actual: { w: inches(3.9), l: inches(3.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x4x6"),
    name: "Schaller 4x6 - 3 inch depth",
    sku: "SCH-346",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(6), h: inches(3) },
    actual: { w: inches(3.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x6x6"),
    name: "Schaller 6x6 - 3 inch depth",
    sku: "SCH-366",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(6), l: inches(6), h: inches(3) },
    actual: { w: inches(5.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
];
