import { BinSpec, binId } from "../index";
import { inches } from "../../geometry/Inches.js";

export const SCHALLER_PART_4: ReadonlyArray<BinSpec> = [
  {
    id: binId("schaller-2x3x6"),
    name: "Schaller 3x6 - 2 inch depth",
    sku: "SCH-236",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(6), h: inches(2) },
    actual: { w: inches(2.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x12"),
    name: "Schaller 3x12 - 2 inch depth",
    sku: "SCH-2312",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(12), h: inches(2) },
    actual: { w: inches(2.9), l: inches(11.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x4x4"),
    name: "Schaller 4x4 - 2 inch depth",
    sku: "SCH-244",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(4), h: inches(2) },
    actual: { w: inches(3.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x4x6"),
    name: "Schaller 4x6 - 2 inch depth",
    sku: "SCH-246",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(4), l: inches(6), h: inches(2) },
    actual: { w: inches(3.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x6x6"),
    name: "Schaller 6x6 - 2 inch depth",
    sku: "SCH-266",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(6), l: inches(6), h: inches(2) },
    actual: { w: inches(5.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
];
