import { BinSpec, binId } from "../bin";
import { inches } from "@storagemaxxing/geometry/Inches";

export const SCHALLER_PART_2: ReadonlyArray<BinSpec> = [
  {
    id: binId("schaller-2x1x2"),
    name: "Schaller 1x2 - 2 inch depth",
    sku: "SCH-212",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.45,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(2), h: inches(2) },
    actual: { w: inches(0.9), l: inches(1.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x3"),
    name: "Schaller 1x3 - 2 inch depth",
    sku: "SCH-213",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.55,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(3), h: inches(2) },
    actual: { w: inches(0.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x4"),
    name: "Schaller 1x4 - 2 inch depth",
    sku: "SCH-214",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.65,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(4), h: inches(2) },
    actual: { w: inches(0.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x1x6"),
    name: "Schaller 1x6 - 2 inch depth",
    sku: "SCH-216",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.85,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(6), h: inches(2) },
    actual: { w: inches(0.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x2"),
    name: "Schaller 2x2 - 2 inch depth",
    sku: "SCH-222",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.65,
    priceApproximate: true,
    nominal: { w: inches(2), l: inches(2), h: inches(2) },
    actual: { w: inches(1.9), l: inches(1.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
];
