import { BinSpec, binId } from "../bin";
import { inches } from "@storagemaxxing/geometry/Inches";

export const SCHALLER_PART_5: ReadonlyArray<BinSpec> = [
  {
    id: binId("schaller-3x1x2"),
    name: "Schaller 1x2 - 3 inch depth",
    sku: "SCH-312",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.55,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(2), h: inches(3) },
    actual: { w: inches(0.9), l: inches(1.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x3"),
    name: "Schaller 1x3 - 3 inch depth",
    sku: "SCH-313",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.7,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(3), h: inches(3) },
    actual: { w: inches(0.9), l: inches(2.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x4"),
    name: "Schaller 1x4 - 3 inch depth",
    sku: "SCH-314",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.85,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(4), h: inches(3) },
    actual: { w: inches(0.9), l: inches(3.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x1x6"),
    name: "Schaller 1x6 - 3 inch depth",
    sku: "SCH-316",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 1.15,
    priceApproximate: true,
    nominal: { w: inches(1), l: inches(6), h: inches(3) },
    actual: { w: inches(0.9), l: inches(5.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-3x2x2"),
    name: "Schaller 2x2 - 3 inch depth",
    sku: "SCH-322",
    vendor: "Schaller",
    system: "schaller",
    catalogSource: "builtin",
    kind: "bin",
    price: 0.85,
    priceApproximate: true,
    nominal: { w: inches(2), l: inches(2), h: inches(3) },
    actual: { w: inches(1.9), l: inches(1.9), h: inches(2.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
];
