import { BinSpec, binId } from "../bin.js";
import { inches } from "@storagemaxxing/geometry/Inches.js";

export const SCHALLER_PART_3: ReadonlyArray<BinSpec> = [
  {
    id: binId("schaller-2x2x3"),
    name: "Schaller 2x3 - 2 inch depth",
    sku: "SCH-223",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(3), h: inches(2) },
    actual: { w: inches(1.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x4"),
    name: "Schaller 2x4 - 2 inch depth",
    sku: "SCH-224",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(4), h: inches(2) },
    actual: { w: inches(1.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x2x6"),
    name: "Schaller 2x6 - 2 inch depth",
    sku: "SCH-226",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(2), l: inches(6), h: inches(2) },
    actual: { w: inches(1.9), l: inches(5.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x3"),
    name: "Schaller 3x3 - 2 inch depth",
    sku: "SCH-233",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(3), h: inches(2) },
    actual: { w: inches(2.9), l: inches(2.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
  {
    id: binId("schaller-2x3x4"),
    name: "Schaller 3x4 - 2 inch depth",
    sku: "SCH-234",
    vendor: "Schaller",
    catalogSource: "builtin",
    nominal: { w: inches(3), l: inches(4), h: inches(2) },
    actual: { w: inches(2.9), l: inches(3.9), h: inches(1.75) },
    tolerance: { w: inches(0.02), l: inches(0.02), h: inches(0.02) },
  },
];
